### ISSUE TITLE
When script not have execution permission the tomee-cli return error.

### ISSUE THREAD

**Issue by danielsoro** [bitmaker-software/tomee-cli#18]
```
tomee-cli.core=> (start)

IOException error=13, Permission denied  java.lang.UNIXProcess.forkAndExec (UNIXProcess.java:-2)
tomee-cli.core=> 
```

The startup/shutdown/version should have execution permission: chmod +x ****.sh 
In Wildfly we had a problem similar with aesh [ https://github.com/aeshell/aesh/commit/dd93f4bec242fa802013ed4a4bf13d1129bb4ebc ]
Maybe we can doing something like this, try set the file as executable before to call it.

**Comment by htmfilho** [comment]
Come on... this is not a bug. The user won't be able to execute those files, with or without tomee-cli, if he doesn't have the right to do so.

If tomee-cli performs a `chmod` we will probably have issues if the user doesn't have permission to perform this command in the informed directory. Also, if we execute this command, we are performing a administrative action out of control of the user.

I think this is only valid when tomee-cli performs the download and installation of TomEE. That's a brand new installation, without deployed apps, etc. But, in this case, this issue is pointing to the wrong feature.

**Comment by danielsoro** [comment]
+1
I'll link it with installation issue and remove bug tag.

**Comment by htmfilho** [comment]
Since issue #16 was fixed, does it fix this one too?

**Comment by danielsoro** [comment]
Sorry @htmfilho 

I forgot to close it.
